[package]
name = "disk_usage_endpoint"
version = "0.1.0"
edition = "2021"

[dependencies]
actix-web = "4.9.0"
env_logger = "0.11.6"
log = "0.4.25"
serde = "1.0.217"
serde_json = "1.0.138"
sys-info = "0.9.1"
tokio = "1.43.0"
